version: "3.7"
services:
  app:
    build:      
      context: ./
      dockerfile: Dockerfile
    image: todos
    container_name: todos-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - todos
  
  db:
    image: mariadb:10.4
    container_name: todos-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel_todos
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"     
    volumes:
      - ./docker-compose/mysql:/var/lib/mysql      
    networks:
      - todos
  
  nginx:
    image: nginx:alpine
    container_name: todos-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - todos

networks:
  todos:
    name: todos
    