version: "3.7"
services:
  app:
    build:      
      context: ./
      dockerfile: Dockerfile
    image: profile
    container_name: profile-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - profile
  
  db:
    image: mariadb:10.4
    container_name: profile-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel_profile
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"     
    volumes:
      - ./docker-compose/mysql:/var/lib/mysql
      # - ./_dump/laravel_profile.sql:/docker-entrypoint-initdb.d/1.sql
    networks:
      - profile
  
  nginx:
    image: nginx:alpine
    container_name: profile-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - profile

networks:
  profile:
    name: profile
    