version: "3.7"
services:
  app:
    build:      
      context: ./
      dockerfile: Dockerfile
    image: forum
    container_name: forum-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - forum
  
  db:
    image: mariadb:10.4
    container_name: forum-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel_forum
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"     
    volumes:
      - ./docker-compose/mysql:/var/lib/mysql      
    networks:
      - forum
  
  nginx:
    image: nginx:alpine
    container_name: forum-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - forum

networks:
  forum:
    name: forum
    